### ISSUE TITLE
Process for adding new 18F team members to 18F analytics

### ISSUE THREAD

**Issue by jackiekazil** [18F/analytics-standards#15]
Do we have one? 
If so, what it is? and should we document? 

/cc @gbinal @ramirezg

**Comment by gbinal** [comment]
https://github.com/18F/analytics/blob/master/guild-tasks.md

**Comment by jackiekazil** [comment]
:+1: @gbinal How are non-GSA folks handled? (I have a couple of requests the Treasury folks from @firebbl1)

**Comment by gbinal** [comment]
Roger - done - 

https://github.com/18F/analytics-standards/blob/master/faq.md#can-i-give-access-to-a-projects-analytics-to-a-client
