### ISSUE TITLE
Include 'agency' parameter on DAP script tag

### ISSUE THREAD

**Issue by konklone** [18F/analytics-standards#16]
The [DAP's integration guide](https://www.digitalgov.gov/files/2015/02/GSA-DAP-UA-Code-Quick-Guide-15-01-30-v1-02_mvf.pdf) requires an `agency` parameter:

![image](https://cloud.githubusercontent.com/assets/4592/8215146/2489b432-14fc-11e5-939a-e2a8d3f86295.png)

That means a tag that looks like this:

``` html
<script id="_fed_an_ua_tag" src="/dap/dap.min.js?agency=GSA"></script>
```

Data gets reported without it, but likely not to the correct sub-profile. So, we should incorporate this into our roll out. I'll be fixing on a couple of properties I've configured without this.

cc @dhcole @gbinal

**Comment by geramirez** [comment]
I'm afraid the information that we have on dap will continue to become outdated. Can we link to main DAP documentation?

**Comment by jackiekazil** [comment]
#### 2 steps
- [ ] 1. Let's add something to standards about this. 
- [ ] 2. Then let's move over to analytics repo and create a task to check all 18F projects to make sure they have this implemented.

**Comment by geramirez** [comment]
@konklone would it be useful to have a DAP snippet generator for agencies? Like a small form that asks what agency you work for and creates the custom snippet?

**Comment by konklone** [comment]
Probably? That sounds like something DAP could and should do, and could make it part of analytics.usa.gov as a single-page thing pretty easily.

**Comment by michelle-rago** [comment]
Agency and sub-agency guidance has been added
