### ISSUE TITLE
Language needs clarification 

### ISSUE THREAD

**Issue by jackiekazil** [18F/analytics-standards#20]
Web services should integrate the api.data.gov service. <--- This line is in the standards, but it doesn't make sense in the flow. I am not sure what api.data.gov has to do with analytics. Add clarification or remove it.

**Comment by gbinal** [comment]
Okay - I've added this language:  https://github.com/18F/analytics-standards/commit/f24f0a729402ab9454d7ed79ef9a5b4783338dd2

**Comment by gbinal** [comment]
Also, more to the point in what you're broaching here, I've re-ordered and clarified the intro section.  

https://github.com/18F/analytics-standards/commit/93ac269b937f92d0a88e8369ceb2121dea434040

**Comment by gbinal** [comment]
I'm going to close for now but feel free to reopen if you feel this isn't addressed.
