### ISSUE TITLE
Which websites to request when filling out DAP Use Reg Form?

### ISSUE THREAD

**Issue by jessieay** [18F/analytics-standards#32]
The FAQ includes a link to the DAP User Reg Form. One of the required fields is this:

![screen shot 2015-09-15 at 1 15 34 pm](https://cloud.githubusercontent.com/assets/601515/9888805/eec3e754-5bab-11e5-9cd6-3e7be60ab1a9.png)

I am not sure what I should put here - is there a standard website or list of sites I should include (I can open a PR to add guidance on this field in the FAQ)

**Comment by jackiekazil** [comment]
That is a loaded question. I can't remember what I put there. 
@gbinal?

**Comment by jackiekazil** [comment]
I recommend `*` :-)

**Comment by gbinal** [comment]
Which website or websites do you primarily run, work on, work with.  In our case, I'd suggest 18f.gsa.gov for our team.  

I've made an edit to clarify this.

**Comment by jessieay** [comment]
Thanks, @gbinal - I see your change was committed at https://github.com/18F/analytics-standards/commit/cb5a4c3048bae2caf06e9b86a355e60b0c5b3c63
