### ISSUE TITLE
Circular Guidance

### ISSUE THREAD

**Issue by thecapacity** [18F/analytics-standards#36]
This page is nonspecific about signing up for analytics, just saying we'll get an email - but the email doesn't give enough information on what to do:

---

You should already have access to 18F's Google Analytics account, but there's another powerful source of web analytics that you can request access to. We wanted to reach out and encourage you to do so.

The [Digital Analytics Program](http://www.digitalgov.gov/services/dap/) (DAP) is a government-wide shared service that is being systematically integrated into all .gov websites. A high-level view of this data can be seen at [analytics.usa.gov](https://analytics.usa.gov/). But as a federal employee, you are able to gain access to the entire underlying data - a tremendous view into how the public uses government websites.  

We encourage every 18F-er to [register for your DAP access](https://github.com/18F/analytics-standards/blob/master/faq.md#how-do-i-get-access-to-the-government-wide-dap-data). It only takes a few minutes and you may find it very useful.  One important note is that you cannot share DAP data outside of government beyond what is visible on [analytics.usa.gov](http://analytics.usa.gov/).
## If you have any questions or need any help, please reach out in the #g-analytics channel in slack.

The link "register for your DAP access" points to this github which points back to the email.

**Comment by thecapacity** [comment]
Actually, I just realized I had _another_ email that said;

`We want to alert you that you have been granted the following access: Collaborate
to the Google Analytics account "..."`

Which is probably what this was refering to - so I think it's maybe ok.

**Comment by gbinal** [comment]
Yep - the analytics guild has been doing pretty well staying on top of giving access to the 18F analytics to new hires.
