### ISSUE TITLE
What are the goals of this project?  

### ISSUE THREAD

**Issue by gbinal** [18F/analytics-standards#4]
Here's what comes to mind for me.  Comment with any thoughts.  
- ~~Articulate norms for edits to the snippet.~~  
- Articulate norms for hosting of the snippet.
- ~~Articulate norms for what gets analytics and when.~~  
- ~~Cover use of api.data.gov by APIs.~~
- ~~Discuss when/how access is given to teammates~~
- ~~Discuss DAP integration.~~

**Comment by jackiekazil** [comment]
This could help us w/ OKRs -- https://docs.google.com/document/d/1ntHEPBUDBR4_S3z0wHiMeplwT_q3RMLqI-hsJN_u2SE/edit
