### ISSUE TITLE
Use Hugo?

### ISSUE THREAD

**Issue by geramirez** [18F/analytics-standards#7]
[CF Notes](https://github.com/18F/cloud-foundry-notes) is set-up using Hugo. Overall it's pretty easy to use because it works with basically the same markdown structure github uses.

**Comment by jackiekazil** [comment]
@gbinal suggested integrating w/ https://pages.18f.gov/guides/ before spinning off, but I am not sure we are quite there yet. 

Yes? No?

**Comment by gbinal** [comment]
I'm in no hurry to make a micro-site but between the docs.18f.gov and pages.18f.gov models, I advise the latter.  It's got greater adoption and consistent use across 18F.

**Comment by jackiekazil** [comment]
Closing this issue. One day we will add to 18F guides, but for now we are just going to add a link -- see #19
